In [1]:
import numpy as np 
import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
# %matplotlib inline

In [2]:
master = pd.read_excel('data/source/master.xlsx', sheet_name='Sheet2', parse_dates=['ENTRY_DATE', 'EFFECTIVE_DATE'])
slave_1 = pd.read_excel('data/source/master.xlsx', sheet_name='Sheet2', parse_dates=['ENTRY_DATE', 'EFFECTIVE_DATE'])
previous_names = master.columns.tolist()
master.head()

,ACCOUNT_CODE,ACCOUNT_NAME,JOURNAL_NUMBER,FSLI,FS_HEADER,ENTRY_DATE,EFFECTIVE_DATE,PERIOD,DEBIT_CREDIT,TRANSACTION_AMOUNT,TRANSACTION_CURRENCY,BASE_AMOUNT,ABS BASE_AMOUNT,BASE_CURRENCY,TRANSACTION_REFERENCE,JOURNAL_TYPE,USER_ID,MANUAL_AUTOMATED,POSTING_DAY
0,3608401,Transmission costs,19763,Admin expenses,Expense,2018-01-03,2017-12-31,2018/001,C,-4003371.0,UGX,-4003371.0,4003371.0,UGX,Data transmission EMTO VODACOM -Dec 17,GL200,GLT,AUTOMATED,Wed
1,2421201,Accruals for invoices from 3rd p. not yet rece...,19763,Accounts payable,Liabilities,2018-01-03,2017-12-31,2018/001,D,4003371.0,UGX,4003371.0,4003371.0,UGX,Data transmission EMTO VODACOM -Dec 17,GL200,GLT,AUTOMATED,Wed
2,3501102,Overtime,19763,Admin expenses,Expense,2018-01-03,2017-12-31,2018/001,C,-5315607.0,UGX,-5315607.0,5315607.0,UGX,Overtime Exp accr Dec 17,GL200,GLT,AUTOMATED,Wed
3,3501102,Overtime,19763,Admin expenses,Expense,2018-01-03,2017-12-31,2018/001,C,-3651355.0,UGX,-3651355.0,3651355.0,UGX,Overtime Exp accr Dec 17,GL200,GLT,AUTOMATED,Wed
4,3501102,Overtime,19763,Admin expenses,Expense,2018-01-03,2017-12-31,2018/001,C,-442169.0,UGX,-442169.0,442169.0,UGX,Overtime Exp accr Dec 17,GL200,GLT,AUTOMATED,Wed

In [1]:
N=5
with open("data/source/all_data.xlsx", 'rb') as myfile:
    head = [next(myfile) for x in range(N)]
# print(head)
# head.head()

FileNotFoundError: [Errno 2] No such file or directory: 'data/source/all_data.xlsx'

In [1]:
import os
file_names = []
file_extensions = []

for f in os.listdir("R:\SPA"):
    file_extensions.append(f)
    file_names.append(f.split(".")[0])
file_names

['Desktop__',
 'FY17',
 'FY18',
 'FY19',
 'FY20',
 'Meetings',
 'RAS Weekly Meetings',
 'Thumbs',
 '~$A Proposals',
 '~$amMate Price list',
 '~$oposals link']

In [5]:
previous_names

['ACCOUNT_CODE',
 'ACCOUNT_NAME',
 'JOURNAL_NUMBER',
 'FSLI',
 'FS_HEADER',
 'ENTRY_DATE',
 'EFFECTIVE_DATE',
 'PERIOD',
 'DEBIT_CREDIT',
 'TRANSACTION_AMOUNT',
 'TRANSACTION_CURRENCY',
 'BASE_AMOUNT',
 'ABS BASE_AMOUNT',
 'BASE_CURRENCY',
 'TRANSACTION_REFERENCE',
 'JOURNAL_TYPE',
 'USER_ID',
 'MANUAL_AUTOMATED',
 'POSTING_DAY']

In [6]:
master = pd.read_excel('data/source/all_data.xlsx')
files = []
file_counter = 0
previous_names = []
for file in file_names:
    file = pd.read_excel("data/source/"+file_extensions[file_counter])
    files.append(file)
    file_counter=file_counter+1
    previous_names.append(file.columns.tolist())

previous_names
file_names
files

[       ACCOUNT_CODE                                       ACCOUNT_NAME  \
 0           3608401                                 Transmission costs
 1           2421201  Accruals for invoices from 3rd p. not yet rece...
 2           3501102                                           Overtime
 3           3501102                                           Overtime
 4           3501102                                           Overtime
 5           3501102                                           Overtime
 6           3501102                                           Overtime
 7           3501102                                           Overtime
 8           3501102                                           Overtime
 9           3501102                                           Overtime
 10          3501102                                           Overtime
 11          2457421                Wages, salaries, severance payments
 12          2421201  Accruals for invoices from 3rd p. not yet rece...
 13          3401221  Exclusive transportation costs third party - Road
 14         C9999999     Creditors with debit balances reclassification
 15          1241701                       Advance Payment to Suppliers
 16          2421201  Accruals for invoices from 3rd p. not yet rece...
 17          3406101  3rd party lease expenses from non cancelable l...
 18          2421201  Accruals for invoices from 3rd p. not yet rece...
 19          3404201     Commissions paid to agents - LUCY Retail Sales
 20          2421201  Accruals for invoices from 3rd p. not yet rece...
 21          3404101                         Commissions paid to agents
 22          2421201  Accruals for invoices from 3rd p. not yet rece...
 23          3613001                             Other commissions paid
 24          2421201  Accruals for invoices from 3rd p. not yet rece...
 25          3608401                                 Transmission costs
 26          2421201  Accruals for invoices from 3rd p. not yet rece...
 27          3608101                                Voice communication
 28          3608101                                Voice communication
 29          3608101                                Voice communication
 ...             ...                                                ...
 600024      2153001                  Net profit or loss for the period
 600025      2151006                Retained Earnings - Opening Balance
 600026      2315124          Non Current Litigation Liability Addition
 600027      2315120                       Non-current litigation costs
 600028      2415105             Year-end closing costs (int & ext) APP
 600029      2415101     Year-end closing costs (internal and external)
 600030      2422112                         External Billing - Inbound
 600031      2422113                        External Billing - Outbound
 600032      2422114                              Transfers to/from NWO
 600033      2422116                                        Network Fee
 600034      2422118                     Network Fee  - Withholding Tax
 600035      2422119                 Exchange Difference on Translation
 600036      2422111                                    Opening Balance
 600037      2422111                                    Opening Balance
 600038      2422111                                    Opening Balance
 600039      2422111                                    Opening Balance
 600040      2422111                                    Opening Balance
 600041      2422111                                    Opening Balance
 600042      1221208                              Trade receivables C90
 600043      1221201                         Trade receivables-Domestic
 600044      1221408                   Allow. for trade receivables C90
 600045      1221401  Allowance doubtful customs charge trade receiv...
 600046      2153529      First time application IFRS 9 IAS Restatement
 600047      2151006                Retained Earnings - Opening Balance
 600048      232400U      Lease liabilities (maturity >1 year) C90  L&B
 600049      232400A      Lease liabilities (maturity >1 year) C10  L&B
 600050      1121103               RoU Land & building Ord Depreciation
 600051      1121108      RoU Land & building Opening balanbce Ord Depr
 600052      112110J               RoU Land & building IAS Restatements
 600053      1121101                RoU Land & building Opening Balance

         JOURNAL_NUMBER                                     FSLI  \
 0                19763                           Admin expenses
 1                19763                         Accounts payable
 2                19763                           Admin expenses
 3                19763                           Admin expenses
 4                19763                           Admin expenses
 5                19763                           Admin expenses
 6                19763                           Admin expenses
 7                19763                           Admin expenses
 8                19763                           Admin expenses
 9                19763                           Admin expenses
 10               19763                           Admin expenses
 11               19763                         Accounts payable
 12               19763                         Accounts payable
 13               19763                            Cost of sales
 14               19820                         Accounts payable
 15               19820                      Accounts receivable
 16               19867                         Accounts payable
 17               19867                           Admin expenses
 18               19867                         Accounts payable
 19               19867                           Admin expenses
 20               19867                         Accounts payable
 21               19867                           Admin expenses
 22               19867                         Accounts payable
 23               19867                           Admin expenses
 24               19867                         Accounts payable
 25               19867                           Admin expenses
 26               19867                         Accounts payable
 27               19867                           Admin expenses
 28               19867                           Admin expenses
 29               19867                           Admin expenses
 ...                ...                                      ...
 600024           31830  share capital and other equity accounts
 600025           31830  share capital and other equity accounts
 600026           31830                         Accounts payable
 600027           31830                               Provisions
 600028           31830                         Accounts payable
 600029           31830                         Accounts payable
 600030           31830                         Accounts payable
 600031           31830                         Accounts payable
 600032           31830                         Accounts payable
 600033           31830                         Accounts payable
 600034           31830                         Accounts payable
 600035           31830                         Accounts payable
 600036           31830                         Accounts payable
 600037           31830                         Accounts payable
 600038           31830                         Accounts payable
 600039           31830                         Accounts payable
 600040           31830                         Accounts payable
 600041           31830                         Accounts payable
 600042           31833                      Accounts receivable
 600043           31833                      Accounts receivable
 600044           31833                      Accounts receivable
 600045           31833                      Accounts receivable
 600046           31833  share capital and other equity accounts
 600047           31833  share capital and other equity accounts
 600048           31833                          Lease Liability
 600049           31833                          Lease Liability
 600050           31837                              Lease asset
 600051           31837                 Accumulated Depreciation
 600052           31837                              Lease Asset
 600053           31837                             Right of Use

                       FS_HEADER ENTRY_DATE EFFECTIVE_DATE    PERIOD  \
 0                       Expense 2018-01-03     2017-12-31  2018/001
 1                   Liabilities 2018-01-03     2017-12-31  2018/001
 2                       Expense 2018-01-03     2017-12-31  2018/001
 3                       Expense 2018-01-03     2017-12-31  2018/001
 4                       Expense 2018-01-03     2017-12-31  2018/001
 5                       Expense 2018-01-03     2017-12-31  2018/001
 6                       Expense 2018-01-03     2017-12-31  2018/001
 7                       Expense 2018-01-03     2017-12-31  2018/001
 8                       Expense 2018-01-03     2017-12-31  2018/001
 9                       Expense 2018-01-03     2017-12-31  2018/001
 10                      Expense 2018-01-03     2017-12-31  2018/001
 11                  Liabilities 2018-01-03     2017-12-31  2018/001
 12                  Liabilities 2018-01-03     2017-12-31  2018/001
 13                      Expense 2018-01-03     2017-12-31  2018/001
 14                  Liabilities 2018-01-03     2017-12-31  2018/001
 15                       Assets 2018-01-03     2017-12-31  2018/001
 16                  Liabilities 2018-01-04     2017-12-31  2018/001
 17                      Expense 2018-01-04     2017-12-31  2018/001
 18                  Liabilities 2018-01-04     2017-12-31  2018/001
 19                      Expense 2018-01-04     2017-12-31  2018/001
 20                  Liabilities 2018-01-04     2017-12-31  2018/001
 21                      Expense 2018-01-04     2017-12-31  2018/001
 22                  Liabilities 2018-01-04     2017-12-31  2018/001
 23                      Expense 2018-01-04     2017-12-31  2018/001
 24                  Liabilities 2018-01-04     2017-12-31  2018/001
 25                      Expense 2018-01-04     2017-12-31  2018/001
 26                  Liabilities 2018-01-04     2017-12-31  2018/001
 27                      Expense 2018-01-04     2017-12-31  2018/001
 28                      Expense 2018-01-04     2017-12-31  2018/001
 29                      Expense 2018-01-04     2017-12-31  2018/001
 ...                         ...        ...            ...       ...
 600024                   Equity 2019-01-24     2018-12-31  2018/013
 600025                   Equity 2019-01-24     2018-12-31  2018/013
 600026              Liabilities 2019-01-24     2018-12-31  2018/013
 600027  Non current liabilities 2019-01-24     2018-12-31  2018/013
 600028              Liabilities 2019-01-24     2018-12-31  2018/013
 600029              Liabilities 2019-01-24     2018-12-31  2018/013
 600030              Liabilities 2019-01-24     2018-12-31  2018/013
 600031              Liabilities 2019-01-24     2018-12-31  2018/013
 600032              Liabilities 2019-01-24     2018-12-31  2018/013
 600033              Liabilities 2019-01-24     2018-12-31  2018/013
 600034              Liabilities 2019-01-24     2018-12-31  2018/013
 600035              Liabilities 2019-01-24     2018-12-31  2018/013
 600036              Liabilities 2019-01-24     2018-12-31  2018/013
 600037              Liabilities 2019-01-24     2018-12-31  2018/013
 600038              Liabilities 2019-01-24     2018-12-31  2018/013
 600039              Liabilities 2019-01-24     2018-12-31  2018/013
 600040              Liabilities 2019-01-24     2018-12-31  2018/013
 600041              Liabilities 2019-01-24     2018-12-31  2018/013
 600042                   Assets 2019-01-24     2018-12-31  2018/013
 600043                   Assets 2019-01-24     2018-12-31  2018/013
 600044                   Assets 2019-01-24     2018-12-31  2018/013
 600045                   Assets 2019-01-24     2018-12-31  2018/013
 600046                   Equity 2019-01-24     2018-12-31  2018/013
 600047                   Equity 2019-01-24     2018-12-31  2018/013
 600048              Liabilities 2019-01-24     2018-12-31  2018/013
 600049              Liabilities 2019-01-24     2018-12-31  2018/013
 600050                   Assets 2019-01-24     2018-12-31  2018/013
 600051                   Assets 2019-01-24     2018-12-31  2018/013
 600052                   Assets 2019-01-24     2018-12-31  2018/013
 600053                   Assets 2019-01-24     2018-12-31  2018/013

        DEBIT_CREDIT  TRANSACTION_AMOUNT TRANSACTION_CURRENCY   BASE_AMOUNT  \
 0                 C       -4.003371e+06                UGX   -4.003371e+06
 1                 D        4.003371e+06                UGX    4.003371e+06
 2                 C       -5.315607e+06                UGX   -5.315607e+06
 3                 C       -3.651355e+06                UGX   -3.651355e+06
 4                 C       -4.421690e+05                UGX   -4.421690e+05
 5                 C       -1.640606e+06                UGX   -1.640606e+06
 6                 C       -2.454550e+05                UGX   -2.454550e+05
 7                 C       -6.661010e+05                UGX   -6.661010e+05
 8                 C       -3.327200e+05                UGX   -3.327200e+05
 9                 C       -2.144023e+06                UGX   -2.144023e+06
 10                C       -2.876420e+05                UGX   -2.876420e+05
 11                D        1.472568e+07                UGX    1.472568e+07
 12                D        1.717498e+08                UGX    1.717498e+08
 13                C       -1.717498e+08                UGX   -1.717498e+08
 14                D        1.060680e+06                UGX    1.060680e+06
 15                C       -1.060680e+06                UGX   -1.060680e+06
 16                D        3.100000e+06                UGX    3.100000e+06
 17                C       -3.100000e+06                UGX   -3.100000e+06
 18                D        1.500000e+07                UGX    1.500000e+07
 19                C       -1.500000e+07                UGX   -1.500000e+07
 20                D        1.200000e+07                UGX    1.200000e+07
 21                C       -1.200000e+07                UGX   -1.200000e+07
 22                D        2.500000e+06                UGX    2.500000e+06
 23                C       -2.500000e+06                UGX   -2.500000e+06
 24                D        9.873390e+05                UGX    9.873390e+05
 25                C       -9.873390e+05                UGX   -9.873390e+05
 26                D        8.659597e+06                UGX    8.659597e+06
 27                C       -5.608830e+05                UGX   -5.608830e+05
 28                C       -9.348000e+04                UGX   -9.348000e+04
 29                C       -4.674020e+05                UGX   -4.674020e+05
 ...             ...                 ...                  ...           ...
 600024            D        4.994003e+08                UGX    4.994003e+08
 600025            C       -4.994003e+08                UGX   -4.994003e+08
 600026            D        3.975120e+08                UGX    3.975120e+08
 600027            C       -3.975120e+08                UGX   -3.975120e+08
 600028            D        8.875000e+07                UGX    8.875000e+07
 600029            C       -8.875000e+07                UGX   -8.875000e+07
 600030            D        2.927493e+08                UGX    2.927493e+08
 600031            C       -2.037214e+09                UGX   -2.037214e+09
 600032            C       -8.389222e+09                UGX   -8.389222e+09
 600033            D        1.094643e+10                UGX    1.094643e+10
 600034            C       -2.271765e+08                UGX   -2.271765e+08
 600035            C       -9.183680e+03                UGX   -9.183680e+03
 600036            C       -2.927493e+08                UGX   -2.927493e+08
 600037            D        2.037214e+09                UGX    2.037214e+09
 600038            D        8.389222e+09                UGX    8.389222e+09
 600039            C       -1.094643e+10                UGX   -1.094643e+10
 600040            D        2.271765e+08                UGX    2.271765e+08
 600041            D        9.183680e+03                UGX    9.183680e+03
 600042            D        3.296394e+07                UGX    3.296394e+07
 600043            C       -3.296394e+07                UGX   -3.296394e+07
 600044            D        3.907805e+05                UGX    3.907805e+05
 600045            C       -3.907805e+05                UGX   -3.907805e+05
 600046            C       -3.335473e+07                UGX   -3.335473e+07
 600047            D        3.335473e+07                UGX    3.335473e+07
 600048            D        3.263050e+09                UGX    3.263050e+09
 600049            C       -3.263050e+09                UGX   -3.263050e+09
 600050            D        1.635895e+09                UGX    1.635895e+09
 600051            C       -1.635895e+09                UGX   -1.635895e+09
 600052            C       -3.263050e+09                UGX   -3.263050e+09
 600053            D        3.263050e+09                UGX    3.263050e+09

         ABS BASE_AMOUNT BASE_CURRENCY                   TRANSACTION_REFERENCE  \
 0          4.003371e+06           UGX  Data transmission EMTO VODACOM -Dec 17
 1          4.003371e+06           UGX  Data transmission EMTO VODACOM -Dec 17
 2          5.315607e+06           UGX                Overtime Exp accr Dec 17
 3          3.651355e+06           UGX                Overtime Exp accr Dec 17
 4          4.421690e+05           UGX                Overtime Exp accr Dec 17
 5          1.640606e+06           UGX                Overtime Exp accr Dec 17
 6          2.454550e+05           UGX                Overtime Exp accr Dec 17
 7          6.661010e+05           UGX                Overtime Exp accr Dec 17
 8          3.327200e+05           UGX                Overtime Exp accr Dec 17
 9          2.144023e+06           UGX                Overtime Exp accr Dec 17
 10         2.876420e+05           UGX                Overtime Exp accr Dec 17
 11         1.472568e+07           UGX                 Overtime Accrual Dec 17
 12         1.717498e+08           UGX                   NTE costs forDec 2017
 13         1.717498e+08           UGX                  NTE costs for Dec 2017
 14         1.060680e+06           UGX               Reclass DR Balance-Dec 17
 15         1.060680e+06           UGX               Reclass DR Balance-Dec 17
 16         3.100000e+06           UGX                    ENHAS-GTW RENT DEC17
 17         3.100000e+06           UGX                    ENHAS-GTW RENT DEC17
 18         1.500000e+07           UGX                         LUCY COMM DEC17
 19         1.500000e+07           UGX                         LUCY COMM DEC17
 20         1.200000e+07           UGX                       AGENTS COMM DEC17
 21         1.200000e+07           UGX                       AGENTS COMM DEC17
 22         2.500000e+06           UGX              DEBT COLLECTION COMM DEC17
 23         2.500000e+06           UGX              DEBT COLLECTION COMM DEC17
 24         9.873390e+05           UGX           UTL-leased line charges DEC17
 25         9.873390e+05           UGX           UTL-leased line charges DEC17
 26         8.659597e+06           UGX                TELEPHONE COST MTN DEC17
 27         5.608830e+05           UGX                TELEPHONE COST MTN DEC17
 28         9.348000e+04           UGX                TELEPHONE COST MTN DEC17
 29         4.674020e+05           UGX                TELEPHONE COST MTN DEC17

In [7]:
files[4]

        User ID                        User Name   Job Title
0           ADI                     Arshad Dilloo        NaN
1           AIK                     Aisha Kadayer        NaN
2           AJN                    Sanjana Luchun        NaN
3           AMY                 Malini MOOTOOSAMY        NaN
4           AOO                   Avishka Bheehoo        NaN
5           BUS               Christine Kobusinge        NaN
6           CHE              Vinella Chengebroyen        NaN
7           CKB              Saifullah Ackbarally        NaN
8           DEG          Devesh Ghoorbin (DHL MU)        NaN
9           DEN                  Yoganaden Ratnan        NaN
10          DEV          Devanee Valydon (DHL MU)        NaN
11          DIR            Dinesh Ramhit (DHL MU)        NaN
12          GKR                  Gundrah Krishtee        NaN
13          INA                    Selvina Subban        NaN
14          KHD                   Maryam Khodabux        NaN
15          KKE               Kelly Chu Chung Kee        NaN
16          KPU                Khemraj Purmessur         NaN
17          KUV                    Kushboo Vaithi        NaN
18          MGO                Maariya Golamhosen        NaN
19          NAC                   Nabil Culcuttee        NaN
20          NIP                     Nitesh Paryag        NaN
21          NME              Narotamsing Meettoo         NaN
22          OP6                      Doreen Nyega        NaN
23          RAU                Rousha Auckburally        NaN
24          RDS               Ridwaan Dosemahamed        NaN
25          ROV                    Romio Muthyalu        NaN
26          SBD      Shaheel Abdoolhakim (DHL MU)        NaN
27          SGO       Sweety Gooriah (DHL MUFSSC)        NaN
28          SOB                       Sooraj Byea        NaN
29          TOP                    Kishen Topassy        NaN
30          VMA     Vusi Madi (DHL Express SSARO)        NaN
31          YDO                 Yasheerah Dowlut         NaN
32          YRA  Yanish Ransbeeharry (DHL MUFSSC)        NaN
33  Grand Total                               NaN        NaN

In [8]:
previous_names

[['ACCOUNT_CODE',
  'ACCOUNT_NAME',
  'JOURNAL_NUMBER',
  'FSLI',
  'FS_HEADER',
  'ENTRY_DATE',
  'EFFECTIVE_DATE',
  'PERIOD',
  'DEBIT_CREDIT',
  'TRANSACTION_AMOUNT',
  'TRANSACTION_CURRENCY',
  'BASE_AMOUNT',
  'ABS BASE_AMOUNT',
  'BASE_CURRENCY',
  'TRANSACTION_REFERENCE',
  'JOURNAL_TYPE',
  'USER_ID',
  'MANUAL_AUTOMATED',
  'POSTING_DAY'],
 ['Trial Balance as at Reporting Period: 2018/012',
  'Unnamed: 1',
  'Unnamed: 2',
  'Unnamed: 3',
  'Unnamed: 4',
  'Unnamed: 5',
  'Unnamed: 6'],
 ['Row Labels', 'Nature of Transaction'],
 ['ACCOUNT_CODE',
  'ACCOUNT_NAME',
  'JOURNAL_NUMBER',
  'FSLI',
  'FS_HEADER',
  'ENTRY_DATE',
  'EFFECTIVE_DATE',
  'PERIOD',
  'DEBIT_CREDIT',
  'TRANSACTION_AMOUNT',
  'TRANSACTION_CURRENCY',
  'BASE_AMOUNT',
  'ABS BASE_AMOUNT',
  'BASE_CURRENCY',
  'TRANSACTION_REFERENCE',
  'JOURNAL_TYPE',
  'USER_ID',
  'MANUAL_AUTOMATED',
  'POSTING_DAY'],
 ['User ID', 'User Name ', 'Job Title']]

In [19]:
from itertools import islice
previous_names = []
with open("data/source/master.xlsx", 'r', errors='ignore') as infile:
    print(infile)
    lines_gen = islice(infile, 2)
    for line in lines_gen:
        print(line)

<_io.TextIOWrapper name='data/source/master.xlsx' mode='r' encoding='cp1252'>
PK     ! |l˜i      [Content_Types].xml ¢(                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Ì”ßjÂ0Æï{‡’ÛÑDŒ1¬^ìÏå&Ì=@ÖœÚ`š„œèôíwuŒÑ)¢°Ý4´Éù¾_O’o8^5&[B@ílÁú¼Ç2°¥SÚÎ

ö6}ÊoY†QZ%³P°5 ./†ÓµÌ¨ÚbÁêýXÖÐHäÎƒ¥™Ê…FFz

In [34]:
import pandas as pd
with pd.read_excel("data/source/master.xlsx") as file:
    print(file)
    data = file.readlines() 
    for line in data: 
        word = line.split() 
        print (word)

KeyboardInterrupt:

In [37]:
# Program extracting all columns 
# name in Python 
import xlrd 
  
loc = ("data/source/master.xlsx") 

column_names = []
  
wb = xlrd.open_workbook(loc) 
sheet = wb.sheet_by_index(0) 
  
# For row 0 and column 0 
sheet.cell_value(0, 0) 
  
for i in range(sheet.ncols): 
    print(sheet.cell_value(0, i)) 
    column_names.append(sheet.cell_value(0, i))
    
column_names

ACCOUNT_CODE
ACCOUNT_NAME
JOURNAL_NUMBER
FSLI
FS_HEADER
ENTRY_DATE
EFFECTIVE_DATE
PERIOD
DEBIT_CREDIT
TRANSACTION_AMOUNT
TRANSACTION_CURRENCY
BASE_AMOUNT
ABS BASE_AMOUNT
BASE_CURRENCY
TRANSACTION_REFERENCE
JOURNAL_TYPE
USER_ID
MANUAL_AUTOMATED
POSTING_DAY

['ACCOUNT_CODE',
 'ACCOUNT_NAME',
 'JOURNAL_NUMBER',
 'FSLI',
 'FS_HEADER',
 'ENTRY_DATE',
 'EFFECTIVE_DATE',
 'PERIOD',
 'DEBIT_CREDIT',
 'TRANSACTION_AMOUNT',
 'TRANSACTION_CURRENCY',
 'BASE_AMOUNT',
 'ABS BASE_AMOUNT',
 'BASE_CURRENCY',
 'TRANSACTION_REFERENCE',
 'JOURNAL_TYPE',
 'USER_ID',
 'MANUAL_AUTOMATED',
 'POSTING_DAY']